sudo: required
dist: xenial

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if ! [[ "$BUILD_TYPE" == "Docs" ]]; then scripts/install_linux_deps.sh ; fi ; fi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/install_osx_deps.sh ; fi

language: cpp

cache: ccache

matrix:
  include:
  - language: cpp
    compiler: gcc
    os: linux
    env: BUILD_TYPE=Coverage  ROW_MAJOR_DEFAULT=OFF
  - language: cpp
    compiler: gcc
    os: linux
    env: BUILD_TYPE=Release ROW_MAJOR_DEFAULT=OFF
  - language: cpp
    compiler: clang
    os: linux
    env: BUILD_TYPE=Debug ROW_MAJOR_DEFAULT=OFF
  - language: cpp
    compiler: gcc
    os: linux
    env: BUILD_TYPE=Debug ROW_MAJOR_DEFAULT=ON
  - language: cpp
    compiler: clang
    os: linux
    env: BUILD_TYPE=Release ROW_MAJOR_DEFAULT=OFF
  - language: cpp
    compiler: clang
    os: osx
    env: BUILD_TYPE=Debug


script:

branches:
  only:
    - master
