name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        string_view: [fmt, std]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 9
      if: matrix.os == 'ubuntu-18.04'

    - name: Install dependencies (Linux)
      run: |
        set -x # echo on
        set -e # exit on error

        cmake --version

        sudo apt-get -qq update
        sudo apt-get install gfortran libc++-dev libgoogle-glog-dev libatlas-base-dev libsuitesparse-dev
        wget https://gitlab.com/libeigen/eigen/-/archive/3.3.4/eigen-3.3.4.tar.bz2
        tar xvf eigen-3.3.4.tar.bz2
        mkdir build-eigen
        cd build-eigen
        cmake ../eigen-3.3.4 -DEIGEN_DEFAULT_TO_ROW_MAJOR=$ROW_MAJOR_DEFAULT
        sudo make install
        git clone https://ceres-solver.googlesource.com/ceres-solver ceres-solver
        cd ceres-solver
        git reset --hard 399cda773035d99eaf1f4a129a666b3c4df9d1b1
        mkdir build
        cd build
        ccache -M 50G
        ccache -s
        cmake -DCXX11=On -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DOPENMP=Off ..
        make -j3
        sudo make install

      if: matrix.os == 'ubuntu-18.04'

    - name: Install dependencies (MacOs)
      run: |
        set -x # echo on
        brew install boost
        git clone https://github.com/google/googletest
        cd googletest
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_STANDARD=11
        make
        sudo make install
        cd ../..
        git clone https://github.com/fmtlib/fmt.git
        cd fmt
        git checkout 6.2.1
        mkdir build
        cd build
        cmake .. -DFMT_TEST=OFF
        make -j2
        sudo make install
        cd ../..
        git clone https://github.com/CLIUtils/CLI11.git
        cd CLI11
        git checkout v1.9.0
        mkdir build
        cd build
        cmake .. -DCLI11_BUILD_TESTS=OFF
        make -j2
        sudo make install
        cd ../..
      if: matrix.os == 'macos-10.15'

    - name: Configure (std::string_view)
      run: |
        set -x # echo on
        cd $GITHUB_WORKSPACE
        git submodule update --init --recursive
        cd tests
        cd ..
        mkdir build
        cd build
        cmake ..
      if: matrix.string_view == 'std'

    - name: Configure (fmt::string_view)
      run: |
        set -x # echo on
        cd $GITHUB_WORKSPACE
        git submodule update --init --recursive
        cd tests
        cd ..
        mkdir build
        cd build
        cmake .. -DUSE_FMT_STRING_VIEW=ON
      if: matrix.string_view == 'fmt'

    - name: Build
      run: |
        set -x # echo on
        cd $GITHUB_WORKSPACE/build
        cmake --build .

    - name: Test
      run: |
        set -x # echo on
        cd $GITHUB_WORKSPACE/build
        make test
