name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    env:
      BUILD_TYPE: Coverage



    steps:
      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies (Linux)
        run: ./scripts/install_linux_deps.sh

      - name: Install Coverage
        run: |
          wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
          tar xf lcov_1.11.orig.tar.gz
          sudo make -C lcov-1.11/ install
          sudo gem install coveralls-lcov

      - name: Run tests for coverage
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          make
          make CTEST_OUTPUT_ON_FAILURE=1 test

      - name: Coveralls
        run:
          set -x
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          lcov --help
          covearlls-lcov --help
          coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
